### ISSUE TITLE
- (EGODatabaseRequest*)requestWith... functions should return autoreleased values

### ISSUE THREAD

**Issue by antonm76** [enormego/egodatabase#14]
Hello!

There is bunch of functions to create EGODatabaseRequest object in EGODatabase.h:
- (EGODatabaseRequest_)requestWithQueryAndParameters:(NSString_)sql, ... NS_REQUIRES_NIL_TERMINATION;
- (EGODatabaseRequest_)requestWithQuery:(NSString_)sql;
- (EGODatabaseRequest_)requestWithQuery:(NSString_)sql parameters:(NSArray*)parameters;
- (EGODatabaseRequest_)requestWithUpdateAndParameters:(NSString_)sql, ... NS_REQUIRES_NIL_TERMINATION;
- (EGODatabaseRequest_)requestWithUpdate:(NSString_)sql;
- (EGODatabaseRequest_)requestWithUpdate:(NSString_)sql parameters:(NSArray*)parameters;

According to Memory Management Policy (https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html) such functions should return autoreleased values, but these ones do not. In fact, I thought they return autoreleased value till checked the implementation.

**Comment by shnhrrsn** [comment]
EGODatabase requires ARC now, if your app doesn't use ARC yet, consider using 1.0: https://github.com/enormego/egodatabase/tree/1.0
